# src/Acme/ApiBundle/Resources/config/doctrine/Product.orm.yml
Acme\ApiBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        price:
            type: decimal
            scale: 2
        description:
            type: text
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
